### PR TITLE
TAS rock classification

### PR DESCRIPTION
**Pull request by NicolasRiel**
Adds a function to retrieve the igneous rock classification using a TAS diagram

### CODE REVIEW

**Comment by boriskaus** [comment]
Thanks a lot - can you add a test for this and also add a documentation page?

**Comment by NicolasRiel** [comment]
Yes, work in progress

**Comment by NicolasRiel** [comment]
Added test and documentation for the TAS classification. Although I am not sure how to compile the doc.

**Comment by boriskaus** [comment]
Thanks a lot!
You can compile it locally by running `make.jl` in `/doc`. Once merged it will be compiled automatically.

In addition it would be really cool if you can add a plotting routine that plots that TAS diagram so you can add your own data on top.
Plotting routines in GeoParams are only made available when the `Plots` package is loaded. For that reason you would have to add your plotting function in `Plotting.jl`.

**Comment by boriskaus** [comment]
you now added 46 files (most related to building the webpage) - can you please remove those?

**Comment by NicolasRiel** [comment]
Progress on plotting function (need a bit more work).
I still have a problem when I compile the doc locally:
"Missing docstring. Missing docstring for GeoParams.TASclassificationData. Check Documenter's build log for details."
It seems it cannot find the documentation of the function, but I do export them and I have the docstring in the TAS routine. Do you have an idea of what I do wrong here?

**Comment by boriskaus** [comment]
yes, this is quite typical. I think it only employs the GeoParams version that is online. 
yet, the docs/build directory should not be added to the repo. We should add that to the .gitignore file

**Comment by NicolasRiel** [comment]
Ah ok, thanks!

**Comment by boriskaus** [comment]
thanks for the modifications - great addition!

**Pull request merged**
