### PR TITLE
Nils edit creep laws

### PR DESCRIPTION
**Pull request by Dr3ven**
I added two dislocation creep laws (Rock salt | Li & Urai (2016) and Salado rock salt | Li & Urai (2016)). Also changed the way the BibTexReference of these laws are stored from the parse_bibtex() function to a simple string containing all the BibTex information. This done to use it in the table output which has been pushed to the main branch. The test fixes should not be merged since new work is being done on the whole creep law system.

### CODE REVIEW

**Comment by boriskaus** [comment]
thanks, this is very useful! 
There are quite a few conflicts, though, that would need to be resolved before this can be merged (see above)

**Comment by Dr3ven** [comment]
I just saw that in the viscosity-dev branch all creep laws are stored in a new file (i.e. DislocationCreep_Data.jl). How shall I adjust my pull request for the predefined creep laws? Is it maybe easier to make a new branch which originates from the viscosity-dev branch in which all implemented creep laws are directly stored in the correct file?

**Comment by boriskaus** [comment]
you would indeed have to follow the new format (and put your changes in the new file). Perhaps it is indeed faster to close this PR and do it again, following the format of `viscosity-dev`

**Comment by Dr3ven** [comment]
I will try to follow the new format then and close this PR.

**Pull request closed without merging**
