### PR TITLE
Iterators for rheology objects  

### PR DESCRIPTION
**Pull request by albert-de-montserrat**
We are starting to have a decent number of generated functions to generate type stable iterations over rheology tuples. To some,  it may not be obvious why we do this or when a generated functions is needed, and to also improve the code readibility, we should try to simplify this process.   Example for a reduction with the new interface:

```julia
@generated function nreduce(f::F, v::NTuple{N, Any}) where {N, F}
    quote
        val = 0.0
        Base.Cartesian.@nexprs $N i -> val += @inbounds f(v[i])
        return val
    end
end

compute_εII_new(v::CompositeRheology, τII, args) = nreduce(vi -> compute_εII(vi, τII, args), v.elements)
```

```julia-repl
v1 = SetDiffusionCreep("Dry Anorthite | Rybacki et al. (2006)")
v2 = SetDislocationCreep("Dry Anorthite | Rybacki et al. (2006)")
v = CompositeRheology(v1,v2)
args = (T=900.0, d=100e-6, τII_old=1e6, dt=1e8)
τII = 2e6

julia> @btime compute_εII($v, $τII, $args)
  31.827 ns (0 allocations: 0 bytes)
7.598120786096899e-21

julia> @btime compute_εII_new($v, $τII, $args)
  31.859 ns (0 allocations: 0 bytes)
7.598120786096899e-21
```

### CODE REVIEW

**Comment by boriskaus** [comment]
this would indeed be very helpful as it reduces the lines of required code. Perhaps something similar can be added for harmonic averages?

**Comment by albert-de-montserrat** [comment]
Given that we dispatch on the type of `v` for harmonic averages, do we need a function for that? With `nreduce` it  simply becomes:
```julia
function compute_harmonic(v::CompositeRheology, EpsII, args)  
    1/nreduce( vi -> _compute_τII_harmonic_element(vi, EpsII, args), v.elements)
end

_compute_τII_harmonic_element(v, EpsII, args) = 1/(first(compute_τII(v, EpsII, args)))
_compute_τII_harmonic_element(v::Union{Parallel, AbstractPlasticity}, EpsII, args) = 0.0
```

**Comment by boriskaus** [comment]
Here an example of how this can be expanded to deal with multiple arguments:
```Julia
@generated function nreduce_args(f::F, v::NTuple{N, Any}, id::NTuple{N,T}, args::NTuple{NT,Any} ) where {N, T<:Integer, NT, F} 
   quote
      val = 0.0
      Base.Cartesian.@nexprs $N i -> val += @inbounds f(v[i], args[id[i]])
      return val
   end
end
```

**Comment by albert-de-montserrat** [comment]
Prototype and example of usage of `nphase` to iterate over material phases
```julia
@generated function nphase(f::F, phase::Int64, v::NTuple{N, Any}) where {N, F}
    quote
        Base.@_inline_meta
        Base.Cartesian.@nexprs $N i -> @inbounds v[i].Phase === phase && return  f(v[i])
        return 0.0
    end
end

compute_εII(MatParam, I, τII, args) = nphase(v_i -> compute_εII(v_i, τII, args), I, MatParam) 

MatParam = (
    SetMaterialParams(Name="Matrix"   , Phase=1,
    CompositeRheology = CompositeRheology(ConstantElasticity(),LinearViscous())), 
    SetMaterialParams(Name="Inclusion", Phase=2,
    CompositeRheology = CompositeRheology(ConstantElasticity(),LinearViscous())),
)

args = ( τII_old=1e6, dt=1e8)
εII, τII = 2e-15, 2e6
```
```julia-repl
 @btime compute_εII($MatParam, $1, $τII, $args)
  3.456 ns (0 allocations: 0 bytes)
```

**Comment by boriskaus** [comment]
changing this from draft to force CI to run

**Review by boriskaus — COMMENTED** [review]
hmm yes, not sure why that was commented

**Review by boriskaus — APPROVED** [review]

**Pull request merged**
