### PR TITLE
Rework rheology database

### PR DESCRIPTION
**Pull request by albert-de-montserrat**
Fixes and addresses #129. The rheology database has been rework;  to make it fully type stable every rheology is contained into his own function. The rheology are organised in the following not exported submodules: `GeoParams.Dislocation`, `GeoParams.Diffusion`, `GeoParams.GBS`, `GeoParams.NonLinearPeierls`,  and `GeoParams.Peierls`. The list of available rheologies can be accessed either by tab completion from the REPL or with:
```julia
diffusion_law_list()
dislocation_law_list()
grainboundarysliding_law_list()
nonlinearpeierls_law_list()
peierls_law_list() 
```

The following example does not allocate anymore
```julia
 function main(Tv, ε̇ii, η)
        # Unit system
        CharDim = SI_units(length=1000m, temperature=1000C, stress=1e7Pa, viscosity=1e20Pas)
        # Configure viscosity model
        flow_nd = SetDislocationCreep(Dislocation.diabase_Caristan_1982, CharDim)
        
        # Setup up viscosity model
        a = @allocated begin
            for i in eachindex(ε̇ii)
                η[i] = compute_viscosity_εII(flow_nd, ε̇ii[i], (;T=Tv[i]))
            end
        end

        return a
    end
   
# Numerical parameters
Ncy = 100
# Allocate arrays
ε0  = 1e-4
Tv  = rand(Ncy+1)
ε̇ii = fill(ε0, Ncy+1) 
η   = zeros(Ncy+1)

@test main(Tv, ε̇ii, η) == 0 # passes
```

### CODE REVIEW

**Comment by boriskaus** [comment]
This is great, thanks a lot!
Some of the tests still indicate allocations though:
```Julia
Allocations: Test Failed at /home/runner/work/GeoParams.jl/GeoParams.jl/test/test_Allocations.jl:43
  Expression: main1(Tv, ε̇ii, η) == 0
   Evaluated: 11782810 == 0
```

**Comment by albert-de-montserrat** [comment]
Looks like it still allocates in 1.6 and 1.7, I don't know if we shuold still support those versions though...

**Comment by albert-de-montserrat** [comment]
Problem is that in those versions the power of a unit is always unstable...

```julia-repl
julia> @code_warntype MPa ^2
MethodInstance for ^(::Unitful.FreeUnits{(MPa,), 𝐌 𝐋⁻¹·⁰ 𝐓⁻²·⁰, nothing}, ::Int64)
  from ^(x::Unitful.FreeUnits{N, D, nothing}, y::Integer) where {N, D} in Unitful at /Users/albert/.julia/packages/Unitful/R4J37/src/units.jl:115
Static Parameters
  N = (MPa,)
  D = 𝐌 𝐋⁻¹·⁰ 𝐓⁻²·⁰
Arguments
  #self#::Core.Const(^)
  x::Core.Const(MPa)
  y::Int64
Locals
  #40::Unitful.var"#40#41"{Int64}
Body::Any
1 ─ %1  = Unitful.:(var"#40#41")::Core.Const(Unitful.var"#40#41")
│   %2  = Core.typeof(y)::Core.Const(Int64)
│   %3  = Core.apply_type(%1, %2)::Core.Const(Unitful.var"#40#41"{Int64})
│         (#40 = %new(%3, y))
│   %5  = #40::Unitful.var"#40#41"{Int64}
│   %6  = Unitful.map(%5, $(Expr(:static_parameter, 1)))::Core.PartialStruct(Tuple{Unitful.Unit{:Pascal, 𝐌 𝐋⁻¹·⁰ 𝐓⁻²·⁰}}, Any[Core.PartialStruct(Unitful.Unit{:Pascal, 𝐌 𝐋⁻¹·⁰ 𝐓⁻²·⁰}, Any[Core.Const(6), Rational{Int64}])])
│   %7  = ::Core.Const()
│   %8  = Core.apply_type(Unitful.FreeUnits, %6, %7)::Type{Unitful.FreeUnits{_A, }} where _A
│   %9  = (%8)()::Unitful.FreeUnits{_A, , nothing} where _A
│   %10 = (*)(%9)::Any
└──       return %10
```

**Comment by boriskaus** [comment]
I’m fine with only supporting newer versions of julia, provided this is made clear in the [compat] part. Note that CI for newer versions also fails because of an unrelated issue

**Review by albert-de-montserrat — COMMENTED** [review]
I addressed the remaining broken tests and allocations are now conditionally tested on >1.7,  so we can keep testing for 1.6 and 1.7.

**Comment by albert-de-montserrat** [comment]
I had to drop 1.6. 1.7 is fine -which was missing in the CI-, and updated Julia compats. Now everything should be working fine.

**Comment by albert-de-montserrat** [comment]
Closes #129

**Review by boriskaus — APPROVED** [review]
Thanks a lot!

**Pull request merged**
