### PR TITLE
Nils edit creep laws

### PR DESCRIPTION
**Pull request by Dr3ven**
I added two dislocation creep laws (Rock salt | Li & Urai (2016) and Salado rock salt | Li & Urai (2016)). Also changed the way the BibTexReference of these laws are stored from the Tuple nested structure of the parse_bibtex() function to a simple string containing all the BibTex information. This done to use it in the table output which has been pushed to the main branch. The test fixes and DislocationCreep.jl commits should not be merged since new work is being done on the whole creep law system.

### CODE REVIEW

**Comment by boriskaus** [comment]
there are still a lot of conflicts that need to be resolved

**Comment by boriskaus** [comment]
conflicts are gone but tests fail.

**Review by albert-de-montserrat — COMMENTED** [review]
Could you put these into a subfolder? i.e. in `src/CreepLaw/data/DiffusionCreep.jl` and  `src/CreepLaw/data/DislocationCreep.jl`

**Comment by albert-de-montserrat** [comment]
Thanks for the PR! Since most of the rheology implementation is still sort of experimental, you shouldn't expect the tests to pass yet.

**Comment by Dr3ven** [comment]
> Could you put these into a subfolder? i.e. in `src/CreepLaw/data/DiffusionCreep.jl` and `src/CreepLaw/data/DislocationCreep.jl`

Surely can do. One quick question though: Are you sure that DiffusionCreep.jl and DislocationCreep.jl should be moved to "data" and not DiffusionCreep_Data.jl and DislocationCreep_Data.jl?

**Comment by albert-de-montserrat** [comment]
Sorry was probably not very clear. I meant to move `DiffusionCreep_Data.jl` into the new subfolder and  rename as  `DiffusionCreep_Data.jl`. It should be enough since the subfolder is already called Data

**Comment by Dr3ven** [comment]
Did I understand it correct with the changes I did? Thanks for the quick answers by the way.

**Comment by albert-de-montserrat** [comment]
Almost :) You could rename `src/Data/DiffusionCreep_Data.jl` as  `src/Data/DiffusionCreep.jl` (and same for dislocation). Since they are in a folder called Data, there is no need to repeat the word Data in the name of the .jl file anymore.

**Pull request merged**
