### PR TITLE
Remove println() calls when CUDA is active

### PR DESCRIPTION
**Pull request by albert-de-montserrat**
`println()` does not work in CUDA kerneles. This PR conditionally loads CUDA with `Requires` and switches off all the calls to `println` when CUDA has been loaded.

### CODE REVIEW

**Review by boriskaus — APPROVED** [review]
great!

**Comment by luraess** [comment]
If needed there is also `@cuprintln` for printing info from within CUDA kernels.

**Comment by albert-de-montserrat** [comment]
@luraess Indeed, but I had problems trying to overload `println` with `@cuprintln`. I guess I can make it work messing around with `eval` calls, but I don't think we want to e.g. print the iterations of every Newton solve in every GPU thread anyway.

**Comment by luraess** [comment]
Sure - was just my 5 cents ;-) I guess it's optimal as you did!

**Pull request merged**
