### PR TITLE
fixes `isbits` error

### PR DESCRIPTION
**Pull request by aelligp**
This fixes several `isbits` errors for newer structs

### CODE REVIEW

**Review by boriskaus — APPROVED** [review]
looks good to me, thanks!

**Comment by aelligp** [comment]
There is something weird going on [here](https://github.com/JuliaGeodynamics/GeoParams.jl/blob/6a0904336975021fbb8a320a2ae5e88a3bcc140e/test/test_Density.jl#L58-L61). 

`Density.jl: Test Failed at /Users/pascalaellig/Documents/PhD/GeoParams.jl/test/test_Density.jl:62
  Expression: num_alloc == 0
   Evaluated: 3815640 == 0

Test Summary: | Pass  Total  Time
Density.jl    |   49     49  7.6s
   Evaluated: 0 == 0`

**Comment by boriskaus** [comment]
I think you should write the test inside the loop, not outside

**Comment by albert-de-montserrat** [comment]
It's a weird case that I dont understand. This

```julia
P = 1.0
T = 1.0
rho = [0.0]
args = (P=P, T=T)
((rho,args) -> begin
    x = ConstantDensity()
    num_alloc = @allocated compute_density!(rho, x, args)
    @test num_alloc == 0
end)(rho,args)
``` 
and 
```julia

let
    rho = [0.0]
    P = 1.0
    T = 1.0
    args = (P=P, T=T)
    x = ConstantDensity()
    num_alloc = @allocated compute_density!(rho, x, args)
    @test num_alloc == 0
end
```

work outside the test suit, but fail when they are inside it... `AllocCheck.jl` also confirms no allocations, but the pkg seems to crash on Julia 1.10+Win10. I would just comment out this test

**Review by albert-de-montserrat — APPROVED** [review]

**Pull request merged**
